Repository dklog-team/dklog-admin, pull requests merged in 2023-06, with the labels that each got.

#44 Feature/admin 42
  src/main/java/kr/dklog/admin/dklogadmin/controller/VisitorController.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/common/ResponseCountDto.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/request/RequestCountByDateDto.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/response/ResponseVisitorStatisticsDto.java
  src/main/java/kr/dklog/admin/dklogadmin/entity/Visitor.java
  src/main/java/kr/dklog/admin/dklogadmin/repository/VisitorRepository.java
  src/main/java/kr/dklog/admin/dklogadmin/service/StatisticsService.java
Labels: feature

#48 Feature/admin 47
  src/main/java/kr/dklog/admin/dklogadmin/entity/Student.java
Labels: feature

#46 Feature/admin 45
  src/main/java/kr/dklog/admin/dklogadmin/controller/PostController.java
  src/main/java/kr/dklog/admin/dklogadmin/controller/StudentController.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/response/ResponseNoAuthStudentDto.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/response/ResponsePopularPostDto.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/response/ResponsePopularPostListDto.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/response/ResponseRecentPostListDto.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/response/ResponseStudentAuthDataDto.java
  src/main/java/kr/dklog/admin/dklogadmin/entity/Student.java
  src/main/java/kr/dklog/admin/dklogadmin/repository/PopularPostInterface.java
  src/main/java/kr/dklog/admin/dklogadmin/repository/PostRepository.java
  src/main/java/kr/dklog/admin/dklogadmin/service/StatisticsService.java
Labels: feature

#49 Feature/admin-43
  src/main/java/kr/dklog/admin/dklogadmin/controller/PostController.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/response/ResponsePostDto.java
  src/main/java/kr/dklog/admin/dklogadmin/entity/Post.java
  src/main/java/kr/dklog/admin/dklogadmin/service/PostService.java
Labels: feature

#52 Feature/admin 45
  src/main/java/kr/dklog/admin/dklogadmin/repository/PostRepository.java
  src/main/java/kr/dklog/admin/dklogadmin/service/StatisticsService.java
Labels: feature

#54 Feature/admin 51
  src/main/java/kr/dklog/admin/dklogadmin/controller/MemberController.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/response/ResponseMemberDto.java
  src/main/java/kr/dklog/admin/dklogadmin/entity/Member.java
  src/main/java/kr/dklog/admin/dklogadmin/entity/Student.java
  src/main/java/kr/dklog/admin/dklogadmin/repository/MemberRepository.java
  src/main/java/kr/dklog/admin/dklogadmin/repository/StudentRepository.java
  src/main/java/kr/dklog/admin/dklogadmin/service/MemberService.java
  src/test/java/kr/dklog/admin/dklogadmin/controller/MemberControllerTest.java
Labels: feature

#56 Feature/admin 55
  src/main/java/kr/dklog/admin/dklogadmin/dto/request/RequestCommentListDto.java
Labels: feature

#68 Feature/admin 61
  src/main/java/kr/dklog/admin/dklogadmin/common/exception/AdminNotFoundException.java
  src/main/java/kr/dklog/admin/dklogadmin/common/exception/DklogException.java
  src/main/java/kr/dklog/admin/dklogadmin/common/exception/DuplicateAdminUsernameException.java
  src/main/java/kr/dklog/admin/dklogadmin/common/exception/InvalidAdminPasswordException.java
  src/main/java/kr/dklog/admin/dklogadmin/common/exception/InvalidAdminUsernameException.java
  src/main/java/kr/dklog/admin/dklogadmin/common/exception/PostNotFoundException.java
  src/main/java/kr/dklog/admin/dklogadmin/controller/AdminController.java
  src/main/java/kr/dklog/admin/dklogadmin/controller/ExceptionController.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/common/ResponseErrorDto.java
  src/main/java/kr/dklog/admin/dklogadmin/service/AuthService.java
Labels: feature

#62 Feature/admin 60
  src/main/java/kr/dklog/admin/dklogadmin/controller/MemberController.java
  src/main/java/kr/dklog/admin/dklogadmin/entity/Member.java
  src/main/java/kr/dklog/admin/dklogadmin/entity/Student.java
  src/main/java/kr/dklog/admin/dklogadmin/repository/StudentRepository.java
  src/main/java/kr/dklog/admin/dklogadmin/service/MemberService.java
Labels: feature, fix

#67 Feature/admin 65
  src/main/java/kr/dklog/admin/dklogadmin/common/util/PagingUtil.java
  src/main/java/kr/dklog/admin/dklogadmin/controller/PostController.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/request/RequestPostDto.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/response/ResponsePostDto.java
  src/main/java/kr/dklog/admin/dklogadmin/entity/Post.java
  src/main/java/kr/dklog/admin/dklogadmin/service/ImageService.java
  src/main/java/kr/dklog/admin/dklogadmin/service/PostService.java
Labels: feature

#66 Feature/admin 64
  src/main/java/kr/dklog/admin/dklogadmin/service/SmsService.java
Labels: feature

#70 Feature/admin 69
  src/main/java/kr/dklog/admin/dklogadmin/dto/request/RequestCommentListDto.java
  src/main/java/kr/dklog/admin/dklogadmin/service/CommentService.java
Labels: feature

#76 Feature/admin 71
  src/main/java/kr/dklog/admin/dklogadmin/common/exception/MemberNotFoundException.java
  src/main/java/kr/dklog/admin/dklogadmin/common/exception/StudentNotFoundException.java
  src/main/java/kr/dklog/admin/dklogadmin/service/MemberService.java
  src/main/java/kr/dklog/admin/dklogadmin/service/StudentService.java
  src/test/java/kr/dklog/admin/dklogadmin/controller/MemberControllerTest.java
  src/test/java/kr/dklog/admin/dklogadmin/controller/StudentControllerTest.java
Labels: feature

#77 Feature/admin 74
  build.gradle
  src/main/java/kr/dklog/admin/dklogadmin/config/CorsConfig.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/response/ResponseRecentPostDto.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/response/ResponseRecentPostListDto.java
  src/main/java/kr/dklog/admin/dklogadmin/entity/Post.java
  src/main/java/kr/dklog/admin/dklogadmin/service/StatisticsService.java
  src/main/resources/application.yml
Labels: feature

#75 Feature/admin 72
  src/main/java/kr/dklog/admin/dklogadmin/controller/ImageController.java
  src/main/java/kr/dklog/admin/dklogadmin/service/ImageService.java
  src/main/java/kr/dklog/admin/dklogadmin/service/PostService.java
Labels: feature

#81 Feature/admin 73
  src/main/java/kr/dklog/admin/dklogadmin/common/exception/CommentNotFoundException.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/request/RequestCommentDeleteDto.java
  src/main/java/kr/dklog/admin/dklogadmin/dto/request/RequestCommentListDto.java
  src/main/java/kr/dklog/admin/dklogadmin/service/CommentService.java
  src/test/java/kr/dklog/admin/dklogadmin/controller/CommentControllerTest.java
Labels: feature

#82 Feature/admin 79
  build.gradle
  src/main/java/kr/dklog/admin/dklogadmin/common/aop/HttpRequestLog.java
  src/main/java/kr/dklog/admin/dklogadmin/common/aop/HttpResponseLog.java
  src/main/java/kr/dklog/admin/dklogadmin/common/aop/LogColor.java
  src/main/java/kr/dklog/admin/dklogadmin/common/exception/SmsResultDataNotFoundException.java
  src/main/java/kr/dklog/admin/dklogadmin/common/exception/UnauthorizedException.java
  src/main/java/kr/dklog/admin/dklogadmin/common/resolver/AuthResolver.java
  src/main/java/kr/dklog/admin/dklogadmin/controller/AdminController.java
  src/main/java/kr/dklog/admin/dklogadmin/controller/AuthController.java
  src/main/java/kr/dklog/admin/dklogadmin/service/CommentService.java
  src/main/java/kr/dklog/admin/dklogadmin/service/SmsService.java
  src/main/java/kr/dklog/admin/dklogadmin/service/StatisticsService.java
Labels: feature

#80 Feature/admin 78
  src/main/java/kr/dklog/admin/dklogadmin/service/ImageService.java
  src/main/java/kr/dklog/admin/dklogadmin/service/PostService.java
  src/test/java/kr/dklog/admin/dklogadmin/controller/PostControllerTest.java
  src/test/java/kr/dklog/admin/dklogadmin/repository/PostRepositoryTest.java
Labels: feature

#83 Feature/admin 70
  src/main/java/kr/dklog/admin/dklogadmin/entity/Post.java
Labels: fix

#85 Feature/admin 84
  .gitignore
  build.gradle
  src/main/resources/application.yml
Labels: feature
